version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - nest-net
    restart: unless-stopped
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - nest-net
    restart: unless-stopped

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: stock
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - nest-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - nest-net

  api-service:
    build:
      context: ./api-service
    container_name: api-service
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - "3000:3000"        # App
      - "9229:9229"        # Debugger port
    networks:
      - nest-net
    volumes:
      - ./api-service:/app
    working_dir: /app
    command: npm run start:debug
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: stock
    restart: unless-stopped

  stock-worker:
    build:
      context: ./stock-worker
    container_name: stock-worker
    depends_on:
      - rabbitmq
    ports:
      - "9230:9229"        # Different port to avoid collision
    networks:
      - nest-net
    volumes:
      - ./stock-worker:/app
    working_dir: /app
    command: npm run start:debug
    environment:
      RABBITMQ_HOST: amqp://guest:guest@rabbitmq:5672
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: stock
    restart: unless-stopped
volumes:
  mysql-data:

networks:
  nest-net:
    driver: bridge